version: '3.0'
services:
  restapi:
    build: ./restapi
    restart: always
    networks:
      - mydockernet
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - CONFIG_USE_DEBUG_MODE
  nginx:
    build: 
      context: ./nginx
      args:
        config_use_certs: ${CONFIG_USE_CERTS}
    restart: always
    networks:
      - mydockernet
    ports:
      - "443:443"
    expose:
      - "443"
    depends_on:
      - restapi
    environment:
      - CONFIG_USE_CERTS
networks:
  mydockernet:
    driver: bridge
